"""empty message

Revision ID: 67262d8dbda1
Revises: f3e477c80527
Create Date: 2020-05-08 12:21:46.549358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67262d8dbda1'
down_revision = 'f3e477c80527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('web_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'web_link')
    op.drop_column('Artist', 'seeking_venues')
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
